[package]
name = "utils"
version = "0.0.0"
edition.workspace = true

[dependencies]
app-surface.workspace = true
bytemuck.workspace = true
cfg-if.workspace = true
env_logger.workspace = true
log.workspace = true
pollster.workspace = true
winit.workspace = true
wgpu.workspace = true
glam.workspace = true
png = "0.17"
image = { version = "*" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook.workspace = true
console_log.workspace = true
js-sys.workspace = true
reqwest = "0.11"
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys = { workspace = true, features = ["Document", "Window", "Element"] }